name: test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest # disabled for now
        raku-version:
          - 'latest'
          - '2020.11'
          - '2021.12'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: zef install --deps-only --/test --test-depends .
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -I. t
